### ISSUE TITLE
[BUG] JumpyBoats lost their jump

### ISSUE THREAD

**Issue by Nutmegan** [sachingorkar102/Tweakin#50]
For the most part, boats no longer jump, but occasionally if you hold down the spacebar the boat will jump after 5-10secs. The duration is sort of sporadic.

Config Settings:
```
jumpy-boats:
  enabled: true
  check-permissions: true
  black-list-worlds: []
  # how high boat should jump (change at your own risk)
  jump-modifier: 0.32
  # cooldown in ticks to make a boat jump (change at your own risk)
  cooldown: 15
```
